% Prompting Game Over annoucement
function gameOver(score, gameFig)
    % Close the game figure
    close(gameFig);

    % Create a custom uifigure for the game over dialog
    fig = uifigure('Name', 'Game Over', 'Position', [200, 200, 600, 300], 'Resize', 'off');
    movegui(fig, 'center');
    
    % Display game over message
    lbl = uilabel(fig, ...
                  'Text', sprintf('Game Over\nYour Score: %d', score), ...
                  'Position', [100, 150, 400, 100], ...
                  'HorizontalAlignment', 'center',...
                  'FontSize', 25, ... 
                  'FontName', 'Arial');
    
    % Create a button that closes the figure
    btn = uibutton(fig, ...
                  'Text', 'OK', ...
                  'Position', [200, 40, 200, 50], ...
                  'ButtonPushedFcn', @(btn,event) closeFigure(fig), ...
                  'FontSize', 25, ...
                  'FontName', 'Lucida Bright');
end

function closeFigure(fig)
    % Close the figure window
    delete(fig);
end